### ISSUE TITLE
Update Tests

### ISSUE THREAD

**Issue by skybluesofa** [skybluesofa/chainable#1]
Update PHP Unit tests to get to at least 90%.

**Comment by jmauerhan** [comment]
I'd love to work on this, I'll start adding some tests and submit a PR :)

**Comment by skybluesofa** [comment]
👍  That was quick!

**Comment by jmauerhan** [comment]
I did notice you just opened this, that was just lucky timing! I happened to open the Hacktoberfest search just at the right time :-)

**Comment by jmauerhan** [comment]
@skybluesofa you don't have phpunit in your composer - what version are you using?

**Comment by skybluesofa** [comment]
I'm running 4.8 on my machine. I'm new to testing and didn't know any better. Suggestions?

**Comment by jmauerhan** [comment]
Yeah definitely want to upgrade to 5, and 5.6 just got marked stable :) I'll add it into composer.json in my PR. Typically you want to commit the composer.lock as well so everyone is on the same exact versions. (https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file).

You run the project specific version by using `vendor/bin/phpunit` instead of just `phpunit`. (This will need to be updated in the travis.yml as well) - this prevents issues with differing versions between individuals and CI.

**Comment by jmauerhan** [comment]
So, upon actually looking at the code that is missing coverage, some of it is unreachable, and some of it is unnecessary. 

It's all part of `methodCallable` which is a private method. In Unit Testing, you don't need to test private methods directly, you should only ever test your public API. So looking at the two public methods which use that private method, they're both magic methods. The uncovered blocks are testing for a null object, testing for a non object, and testing for a null method name.

To my knowledge, there's no way that either `__call` or `__callStatic` could be called with the method name being null. This block will never be reached. By changing the signature of the private method to:
`private function methodCallable($object, string $method)` you can remove the need for the check within this method. Because the method is private, it can't be used by any other class, and you have the security that anyone using it basically knows how to use it. (This applies to the check for a null object as well). 

The final check is the is_object check, that one I _think_ you can remove the need for that logic by typehinting `private function methodCallable(Chainable $object, string $method)` but I can't recall if you can typehint on a trait and I haven't tried it yet. Probably not with my luck :) If not, the way to test this involves actually using the private method incorrectly, and I'll work on a test for that. 

I'll submit a PR that reflects these changes - obviously feel free to ignore any of this, just offering up my advice :)

**Comment by jmauerhan** [comment]
Oh also, is there a reason the methods in your test class do not have `public` visibility explicitly written? Since the trait uses `public` I was confused why you didn't apply that to your test as well.

**Comment by skybluesofa** [comment]
Just an oversight on adding `public` to the tests. I've updated visibility.

Thanks again for your help.

**Comment by jmauerhan** [comment]
It looks like Code Climate's tool handles the difference, because it shows the same report as phpdbg, so you're now at 100! ⭐️ 

Was happy to help, I look forward to seeing your progress on this repo in the future!
